- fix in checking is netforking is up.
Changed files:
    postgresql.init -> 1.5

diff --git a/postgresql.init b/postgresql.init
--- a/postgresql.init
+++ b/postgresql.init
@@ -22,7 +22,10 @@
 [ -f /etc/sysconfig/postgresql ] && . /etc/sysconfig/postgresql
 
 # Check that networking is up.
-[ "${NETWORKING}" = "no" ] && echo "Error: Networking is down" && exit 0
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Postgresql service can't be runed."
+	exit 1
+fi
 
 # Sanity check
 [ -f /tmp/.s.PGSQL.5432 ] || rm -f /tmp/.s.PGSQL.5432
