- merged DEVEL branch
Changed files:
    postgresql-conf.patch -> 1.2
    postgresql-configure.patch -> 1.8
    postgresql-link.patch -> 1.2
    postgresql-pg_ctl-nopsql.patch -> 1.2
    postgresql.spec -> 1.218

diff --git a/postgresql-pg_ctl-nopsql.patch b/postgresql-pg_ctl-nopsql.patch
--- a/postgresql-pg_ctl-nopsql.patch
+++ b/postgresql-pg_ctl-nopsql.patch
@@ -1,6 +1,6 @@
---- src/bin/pg_ctl/pg_ctl.sh 	Sat Sep 29 05:09:32 2001
-+++ src/bin/pg_ctl/pg_ctl.sh.mis	Mon Mar 24 23:16:48 2002
-@@ -96,12 +96,12 @@
+--- src/bin/pg_ctl/pg_ctl.sh.orig	2003-08-05 01:59:39.000000000 +0200
++++ src/bin/pg_ctl/pg_ctl.sh	2003-08-08 22:04:34.000000000 +0200
+@@ -98,12 +98,12 @@
  fi
  
  # Check if needed programs actually exist in path
@@ -11,21 +11,8 @@
 +elif [ -x "$bindir/postmaster" ]; then
      PGPATH="$bindir"
  else
--    echo "The programs 'postmaster' and 'psql' are needed by $CMDNAME but" 1>&2
-+    echo "The program 'postmaster' is needed by $CMDNAME but" 1>&2
-     echo "were not found in the directory '$bindir'." 1>&2
+-    echo "The programs \"postmaster\" and \"psql\" are needed by $CMDNAME but" 1>&2
++    echo "The programs \"postmaster\" is needed by $CMDNAME but" 1>&2
+     echo "were not found in the directory \"$bindir\"." 1>&2
      echo "Check your installation." 1>&2
      exit 1
-@@ -370,8 +370,10 @@
- # 6) If the dynamic loader is not set up correctly (for this user/at
- #    this time), psql will fail (to find libpq).
- # 7) If psql is misconfigured, this may fail.
--	    if "$PGPATH/psql" -l >/dev/null 2>&1
--	    then
-+
-+# YES, this is horribly misconceived.
-+
-+	    if ps -C postmaster >/dev/null 2>&1; then
- 		break;
- 	    else
- 		$silence_echo $ECHO_N "."$ECHO_C
